### PR TITLE
you can now sort leader by name and distance

### PR DESCRIPTION
**Pull request by Ohior**
Clicking the sort in item in menu display a drop down menu that enables user to sort by name or distance 

studio64_2Qb6SLkSZS
studio64_kR5FoNCRCa
screenshot of sorting by name and distance

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
seems like a great job @Ohior can you send the apk please , i would love to see what you have come up with

**Comment by Ohior** [comment]
> seems like a great job @Ohior can you send the apk please , i would love to see what you have come up with

This is the zip file that contains the app-debug.apk and output-metadata.json
[debug.zip](https://github.com/PratyushSingh07/cyclofit/files/10263616/debug.zip)

**Comment by PratyushSingh07** [comment]
hey @Ohior you have done a commendable job but after the list is sorted the indices are set to 0 for every person ,that shouldn't be happening. After sorting the indices should be in the ascending order always (1 to n).

**Comment by Ohior** [comment]
> hey @Ohior you have done a commendable job but after the list is sorted the indices are set to 0 for every person ,that shouldn't be happening. After sorting the indices should be in the ascending order always (1 to n).

Let me work on that to fix the indexing bug

**Pull request closed without merging**
